// frontend/lib/labels.ts
// 集中化 UI 文案與術語白話解讀。各頁引用此處,杜絕散落的硬編字串(尤其中英混雜)。
// 金融慣用詞(Sharpe/RSI/CAGR)保留原詞,解讀放 GLOSSARY。

export const L = {
  common: { run: "執行", loading: "執行中…", more: "更多", advanced: "進階分析", noData: "無資料" },
  market: { title: "市場行情", symbol: "商品", timeframe: "週期", live: "即時", paused: "已暫停", offlineCsv: "離線資料(CSV)" },
  backtest: {
    title: "模擬回測",
    run: "執行回測",
    compare: "比較全部策略",
    optimize: "參數最佳化",
    walkforward: "樣本外驗證",
    rangeRecent: "最近 N 根",
    rangeDates: "日期區間",
    overview: "概覽",
    trades: "交易明細",
    excess: "超額(策略 − 大盤)",
    noTrades: "此區間策略未產生任何交易",
  },
  metrics: {
    total_return: "總報酬",
    buy_hold: "Buy & Hold",
    cagr: "年化報酬 CAGR",
    max_drawdown: "最大回撤",
    sharpe: "Sharpe",
    sortino: "Sortino",
    calmar: "Calmar",
    win_rate: "勝率",
    profit_factor: "獲利因子",
    annualized_volatility: "年化波動",
    exposure: "曝險時間",
    turnover: "週轉率",
    max_consecutive_losses: "最大連虧",
    num_trades: "交易數",
  },
  nav: {
    strategyLab: "策略室",
    strategyLabSub: "Strategy Lab",
    tradingRoom: "交易室",
    tradingRoomSub: "Trading Room",
    tools: "工具",
    toolsSub: "Tools",
    library: "策略庫",
    librarySub: "Strategy Library",
    libraryEmpty: "尚無已存策略",
    libraryError: "策略庫載入失敗",
  },
  onboarding: {
    title: "三步上手",
    dismiss: "知道了",
    step1Title: "① 策略室設計",
    step1Body: "與 AI 對話,生成你的交易策略並存入策略庫。",
    step2Title: "② 交易室回測",
    step2Body: "把策略拿去回測,看 K 線買賣點與績效指標。",
    step3Title: "③ 排程 / 實盤",
    step3Body: "把驗證過的策略接上工作流,排程自動執行。",
  },
  portfolio: {
    title: "投組",
    cash: "現金",
    positions: "部位市值",
    equity: "權益",
    resetPaper: "重置紙上帳戶",
    error: "投組載入失敗",
    loading: "載入中…",
    recentOrders: "近期訂單",
    noOrders: "尚無訂單紀錄。",
    colSymbol: "代號",
    colQty: "數量",
    colAvg: "均價",
    colPrice: "現價",
    colUpnl: "未實現損益",
  },
  schedules: {
    title: "排程(自動執行)",
    selectWorkflow: "請先選擇已儲存的工作流(於上方建立器存檔)。",
    workflow: "工作流",
    selectPlaceholder: "— 選擇 —",
    everySeconds: "間隔(秒)",
    schedule: "建立排程",
    colInterval: "間隔",
    colState: "狀態",
    colLastRun: "上次執行",
    colLastStatus: "上次結果",
    running: "執行中",
    paused: "已暫停",
    delete: "刪除",
    empty: "尚無排程。先在建立器存檔工作流,再於此排程。",
  },
  notifications: {
    title: "通知",
    test: "測試",
    empty: "尚無通知。訂單與訊號會顯示在這裡。",
  },
  dataImport: {
    symbolPlaceholder: "代號(如 2330 / AAPL)",
  },
} as const;

// 每個指標一句白話(主+次全覆蓋)。<Term> 以 hover tooltip 呈現。
export const GLOSSARY: Record<string, string> = {
  total_return: "整段期間的總損益百分比。",
  buy_hold: "同期間「買進並持有」不操作的報酬,用來比較策略有沒有贏大盤。",
  cagr: "把總報酬換算成每年平均的複利成長率,跨不同長度才好比較。",
  max_drawdown: "從資產高點跌到後續低點的最大跌幅;越小代表越穩、越不會睡不著。",
  sharpe: "風險調整後報酬;>1 算不錯,接近 0 普通,<0 代表承擔波動卻虧損。",
  sortino: "類似 Sharpe,但只計算「下跌」的波動,對下檔風險更敏感。",
  calmar: "年化報酬 ÷ 最大回撤;衡量「賺的相對於最痛的那一跌」划不划算。",
  win_rate: "獲利交易佔總交易的比例。注意:勝率高 ≠ 賺錢(可能小賺多次、大賠一次)。",
  profit_factor: "總獲利 ÷ 總虧損;>1 才有正期望值,∞ 代表期間內沒有虧損交易。",
  annualized_volatility: "報酬的年化標準差;數字越大代表淨值上下震盪越劇烈。",
  exposure: "有持倉的時間佔比;100% 代表幾乎全程在場,低代表多在空手等訊號。",
  turnover: "交易頻繁度;越高代表進出越勤、累積的交易成本越多。",
  max_consecutive_losses: "連續虧損的最長次數;反映策略最糟的一段心理壓力。",
  num_trades: "完整進出場的交易筆數;太少則統計不具代表性。",
  walk_forward: "用過去資料選參數、在「沒看過的未來」資料上驗證,專門抓出過度最佳化。",
  optimize: "掃描參數網格找最佳組合;本系統以樣本外(OOS)指標排名,避免挑到過擬合的參數。",
};
